Makefile, elvis.config, erlang.mk, src/sumo.erl, src/sumo_app.erl, src/sumo_backend_elasticsearch.erl, src/sumo_backend_mongo.erl, src/sumo_backend_mysql.erl, src/sumo_internal.erl, src/sumo_sql_builder.erl, src/sumo_store.erl, src/sumo_store_elasticsearch.erl, src/sumo_store_mongo.erl, src/sumo_store_mysql.erl, src/sumo_store_pgsql.erl, src/sumo_sup.erl
=> Code cleanup

src/sumo_store.erl
Delete function and callback were removed from module `sumo_store.erl`.
=> [Fixed #110] Remove delete function and callback from sumo_store.

CHANGELOG.md, Makefile, src/sumo_db.app.src
use [Github-Changelog-Generator](https://github.com/skywinder/Github-Changelog-Generator)
=> Automate CHANGELOG.md

src/sumo_db.app.src
=> Fixed VSN.

CHANGELOG.md
=> [#ISSUE] Updated Changelog.

CHANGELOG.md, src/sumo_db.app.src
Fix  #159 Version bump to 0.3.7
=> [Fix #159] Version bump to 0.3.7

CHANGELOG.md, src/sumo_db.app.src
=> Version Bump 0.3.11

CHANGELOG.md, src/sumo_db.app.src
=> Version Bump to 0.3.13

Makefile, src/sumo_store_riak.erl, test/riak/nested_docs_SUITE.erl, test/riak/riak_test.config, test/riak/sumo_test_purchase_order.erl
- Unified sumo_db-riak-extras project with sumo_db.
- Added nested docs tests (taken from sumo_db-riak-extras).
=> Unified sumo_db-riak-extras project with sumo_db

Makefile, erlang.mk, src/sumo_backend_mysql.erl, src/sumo_backend_sup.erl, src/sumo_store_elasticsearch.erl, src/sumo_store_mongo.erl, src/sumo_store_mysql.erl, src/sumo_store_sup.erl, src/sumo_sup.erl
This app doesn't compile with the latest version of erlang.mk
=> Upgrade erlang.mk and get the app to compile

test/sumo_test_people_mnesia.erl, test/sumo_test_people_mongo.erl, test/sumo_test_people_mysql.erl, test/sumo_test_people_pgsql.erl, test/sumo_test_people_riak.erl
=> Tests for #216

src/sumo_store_mongo.erl, src/sumo_store_riak.erl, test/riak/riak_test.config, test/sumo_test_people_riak.erl
This PR also fix issues #225 and #226.
=> Cabol.222.fix riak to work with data types

src/adapters/sumo_store_mnesia.erl, src/sumo.erl, test/sumo_test_people_mnesia.erl
[Fix #251] Simplify strings handling.
=> [Fix #251] Simplify strings handling.

src/adapter_test_helpers/sumo_basic_test_helper.erl, src/adapter_test_helpers/sumo_test_people.erl, src/sumo.erl, test/sumo_test_people_mnesia.erl
[Fix #250] Support `boolean` data type.
=> [Fix #250] Support `boolean` data type.

src/adapter_test_helpers/sumo_find_test_helper.erl
=> [#257] find_test_helper adapted to last changes in sumo_db

src/adapter_test_helpers/sumo_basic_test_helper.erl, src/adapter_test_helpers/sumo_events_test_helper.erl, src/adapter_test_helpers/sumo_test_people_events_manager.erl, src/adapters/sumo_store_mnesia.erl, src/sumo.erl, src/sumo_config.erl, src/sumo_event.erl, src/sumo_event_manager_sup.erl, src/sumo_store.erl, src/sumo_sup.erl, test/sumo_basic_SUITE.erl, test/sumo_events_SUITE.erl, test/sumo_test_people_mnesia_events_handler.erl, test/test.config
This was done to enable time measuring for queries tracked by sumo_db
Wombat plugin: https://github.com/esl/wombat/pull/2366
=> Add pre_events and their dispatching

CHANGELOG.md, src/sumo_db.app.src
=> [#282] Version Bump to 0.7.0

CHANGELOG.md, src/sumo_db.app.src
=> [#286] Version Bump to 0.7.1

.editorconfig, CONTRIBUTING.md
Follows https://github.com/inaka/sumo_db_riak/pull/17
=> Mention guidelines

README.md, elvis.config, src/adapter_test_helpers/sumo_test_people.erl, src/adapters/sumo_backend_mnesia.erl, src/adapters/sumo_store_mnesia.erl, src/sumo.erl, src/sumo_internal.erl, src/utils/sumo_sql_builder.erl, src/utils/sumo_utils.erl, test/sumo_test_utils.erl
[#275] – Remove the need for mnesia's start_phase magic
=> [#275] – Remove the need for mnesia's start_phase magic

src/sumo_db.app.src, test/test.config
=> [WIP] Remove dependency on sasl

CHANGELOG.md, src/sumo_db.app.src
=> [#310] Version Bump to 0.7.2

README.md, examples/custom_store/README.md, examples/custom_store/config/sys.config, examples/custom_store/rebar.config, examples/custom_store/src/our_pgsql_store.erl, examples/custom_store/src/person.erl, examples/custom_store/src/store_example.app.src, examples/custom_store/src/store_example.erl, examples/custom_store/src/store_example_sup.erl
=> [#313] Own store example

CHANGELOG.md, src/sumo_db.app.src
=> [#318] Version Bump to 0.7.3

.gitignore, CHANGELOG.md, rebar.config, rebar.lock, src/sumo_db.app.src
=> Version Bump to 0.7.4

src/sumo_db.app.src
=> Version Bump to 0.7.4.1

src/sumo_db.app.src
=> Version Bump to 0.7.5
